name: Build and publish emscripten

on:
  push:
    branches: [ emscripten ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: mymindstorm/setup-emsdk@v11
    - uses: actions/checkout@v3

    - name: Verify
      run: emcc -v
      
    - name: Install dependencies
      run: make web
