name: Build and publish emscripten

on:
  push:
    branches: [ emscripten ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: lovasoa/setup-emscripten@master
      with:
        emscripten-version: '1.38.47'
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: make web
