name: Build and publish emscripten

on:
  push:
    branches: [ emscripten ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: mymindstorm/setup-emsdk@v11
    - uses: actions/checkout@v3

    - name: Verify emcc
      run: emcc -v
      
    - name: Build
      run: make web
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target